gallery/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from stream.views import action_list

urlpatterns = patterns(
    '',
    url(r'^$', action_list, name='home'),
    url(r'^auth/', include('accounts.urls', 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('photos.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.conf.urls import patterns, url

from photos import views
from photos.views import album, photo, person, location

urlpatterns = patterns(
    '',
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<query>[\w=&]+)/$', views.results, name='results'),

    url(r'^albums/$', album.list, name='albums'),
    url(r'^albums/create.ajax/$', album.create, name='album_create'),
    url(r'^albums/(?P<pk>\d+)/$', album.detail, name='album'),
    url(r'^albums/(?P<pk>\d+)/edit.ajax/$', album.edit, name='album_edit'),
    url(r'^albums/(?P<pk>\d+)/delete.ajax/$', album.delete,
        name='album_delete'),
    url(r'^albums/(?P<pk>\d+)/merge.ajax/$', album.merge,
        name='album_merge'),
    url(r'^albums/(?P<pk>\d+)/download/$', album.download,
        name='album_download'),

    url(r'^locations/$', location.list, name='locations'),
    url(r'^locations/create.ajax/$', location.create,
        name='location_create'),
    url(r'^locations/(?P<pk>\d+)/$', location.detail, name='location'),
    url(r'^locations/(?P<pk>\d+)/rename.ajax/$', location.rename,
        name='location_rename'),
    url(r'^locations/(?P<pk>\d+)/delete.ajax/$', location.delete,
        name='location_delete'),

    url(r'^people/$', person.list, name='people'),
    url(r'^people/create.ajax/$', person.create, name='person_create'),
    url(r'^people/(?P<pk>\d+)/$', person.detail, name='person'),
    url(r'^people/(?P<pk>\d+)/rename.ajax/$', person.rename,
        name='person_rename'),
    url(r'^people/(?P<pk>\d+)/delete.ajax/$', person.delete,
        name='person_delete'),

    url(r'^photos/(?P<pk>\d+)/$', photo.detail, name='photo'),
    url(r'^photos/(?P<pk>\d+)/rotate.ajax/$', photo.rotate,
        name='photo_rotate'),
    url(r'^photos/(?P<pk>\d+)/move.ajax/$', photo.move, name='photo_move'),
    url(r'^photos/(?P<pk>\d+)/rename.ajax/$', photo.rename,
        name='photo_rename'),
    url(r'^photos/(?P<pk>\d+)/tag.ajax/$', photo.tag, name='photo_tag'),
    url(r'^photos/(?P<pk>\d+)/delete.ajax/$', photo.delete,
        name='photo_delete'),
    url(r'^photos/(?P<pk>\d+)/download/$', photo.download,
        name='photo_download'),

    # alternate ways to get to an album
    url(r'^locations/(?P<location_pk>\d+)/albums/(?P<pk>\d+)/$',
        album.detail, name='album'),

    # alternate ways to get to a photo
    url(r'^locations/(?P<location_pk>\d+)/albums/(?P<album_pk>\d+)/photos/(?P<pk>\d+)/$',
        photo.detail, name='photo'),
    url(r'^people/(?P<person_pk>\d+)/photos/(?P<pk>\d+)/$', photo.detail,
        name='photo'),
    url(r'^search/(?P<query>[\w=&]+)/photos/(?P<pk>\d+)/$', photo.detail,
        name='photo'),
)

photos/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

from utils.filestorage.uploads import get_unique_upload_path
from utils.filestorage.signals import delete_files_on_delete, \
    delete_files_on_change
from photos.utils import generate_thumbnail

MONTH_CHOICES = ((mon, datetime.date(2000, mon, 1).strftime('%B')) for mon in
                 range(1, 13))

YEAR_CHOICES = ((year, year) for year in
                range(1950, (datetime.datetime.now().year + 1)))


class Location(models.Model):
    """A location is a physical location that can be applied to an album."""

    name = models.CharField(_('name'), max_length=200)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('location')
        verbose_name_plural = _('locations')

    @models.permalink
    def get_absolute_url(self):
        return ('location', [str(self.id)])

    def __str__(self):
        return self.name

    @property
    def cover_photo(self):
        """
        Returns the cover photo for this person, which for now is just the
        first photo from the first album based on whatever ordering is the
        default.
        """
        return self.album_set.first().photo_set.first()


class Person(models.Model):
    """A person is an actual person that can be tagged in photos."""

    name = models.CharField(_('name'), max_length=200)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('person')
        verbose_name_plural = _('people')

    @models.permalink
    def get_absolute_url(self):
        return ('person', [str(self.id)])

    def __str__(self):
        return self.name

    @property
    def cover_photo(self):
        """
        Returns the cover photo for this person, which for now is just the
        first photo based on whatever ordering is the default.
        """
        return self.photo_set.first()


class Album(models.Model):
    """
    An album is a collection of photos. It belongs to a location and can also
    have a month and a year associated with it.
    """

    name = models.CharField(_('name'), max_length=200)
    month = models.PositiveSmallIntegerField(
        _('month'), null=True, blank=True, choices=MONTH_CHOICES)
    year = models.PositiveSmallIntegerField(
        _('year'), null=True, blank=True, choices=YEAR_CHOICES)

    location = models.ForeignKey(
        Location, null=True, blank=True,
        verbose_name=_('location'), on_delete=models.SET_NULL)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('album')
        verbose_name_plural = _('albums')

    @models.permalink
    def get_absolute_url(self):
        return ('album', [str(self.id)])

    def __str__(self):
        return self.name

    @property
    def cover_photo(self):
        """
        Returns the cover photo for this album, which for now is just the
        first photo based on whatever ordering is the default.
        """
        return self.photo_set.first()

    def get_date_display(self):
        """
        Returns a pretty display of the month and year in one of the formats:
        - 'January 2014'
        - 'January'
        - '2014'
        """
        output = []
        if self.month:
            output.append(str(self.get_month_display()))
        if self.year:
            output.append(str(self.get_year_display()))
        return ' '.join(output)


class Photo(models.Model):
    """
    A photo is just that - a single photo. It can belong to only one album.
    """

    name = models.CharField(_('name'), max_length=200, null=True, blank=True)
    file = models.ImageField(_('file'), upload_to=get_unique_upload_path)

    album = models.ForeignKey(Album, verbose_name=_('album'))
    people = models.ManyToManyField(
        Person, blank=True, verbose_name=_('people'))

    # exif_make = models.CharField(max_length=100, null=True, blank=True)
    # exif_model = models.CharField(max_length=100, null=True, blank=True)
    # exif_iso = models.PositiveSmallIntegerField(null=True, blank=True)
    # exif_focal = models.PositiveSmallIntegerField(null=True, blank=True)
    # exif_exposure = models.CharField(max_length=100, null=True, blank=True)
    # exif_fnumber = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('photo')
        verbose_name_plural = _('photos')

    @models.permalink
    def get_absolute_url(self):
        return ('photo', [str(self.id)])

    def __str__(self):
        return self.name

    def thumbnail(self, size):
        """
        Generate and return a thumbnail with the given size. Only do this once
        in this instance to save on hits to the Thumnail model.
        """
        prop_name = '_thumbnail_%s' % size.replace('-', '_')
        if not hasattr(self, prop_name):
            setattr(
                self,
                prop_name,
                self.thumbnail_set.get_or_create(size=size)[0].file)
        return getattr(self, prop_name)

    @property
    def file_200x200(self):
        """
        Shortcut to generate a '200x200-fit' thumbnail. Useful in templates.
        """
        return self.thumbnail('200x200-fit')

    @property
    def file_800x600(self):
        """
        Shortcut to generate a '800x600-thumb' thumbnail. Useful in templates.
        """
        return self.thumbnail('800x600-thumb')


class Thumbnail(models.Model):
    """
    A thumbnail is a smaller resolution size of a photo. It knows how to
    generate itself once it has a size and a photo associated to it.
    """

    size = models.CharField(_('size'), max_length=20, db_index=True)
    file = models.ImageField(_('file'))
    photo = models.ForeignKey(Photo, verbose_name=_('photo'))

    class Meta:
        ordering = ['photo', 'size', ]
        unique_together = ('photo', 'size', )
        verbose_name = _('thumbnail')
        verbose_name_plural = _('thumbnails')

    def __str__(self):
        return '%s (%s)' % (self.photo, self.size)

    def generate(self):
        """
        Generate the thumbnail. This happens regardless of whether we already
        have one generated. The new one will overwrite the existing one (while
        keeping the same filename).
        """
        self.file = generate_thumbnail(self.photo.file, self.size)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        """
        If we have a photo and a size, generate a thumbnail regardless of
        whether we already have one generated. Maybe in the future this could
        check to make sure the thumbnail already exists, but that's
        not needed now.
        """
        if self.photo and self.size:
            self.generate()
        super().save(force_insert, force_update, using, update_fields)

# Delete photo files when Photo instance is deleted.
models.signals.pre_delete.connect(delete_files_on_delete, sender=Photo)
models.signals.pre_save.connect(delete_files_on_change, sender=Photo)

# Delete thumbnail files when Thumbnail is deleted.
models.signals.pre_delete.connect(delete_files_on_delete, sender=Thumbnail)
models.signals.pre_save.connect(delete_files_on_change, sender=Thumbnail)

photos/views/album.py
import os
import tempfile
import zipfile

from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from photos.forms import AlbumForm, AlbumMergeForm
from photos.models import Album, Location
from photos.views import get_photo_queryset
from utils.paginate import paginate
from utils.views import json_redirect, json_render


def get_back_link(request, album, **kwargs):
    """
    Determines the back link for an album.
    - If the URL is /locations/<id>/albums/<id>/ then go back to the location.
    - If the URL is /albums/<id>/ then go back to the album list.
    """
    if 'location_pk' in kwargs:
        location = get_object_or_404(Location, pk=kwargs.get('location_pk'))
        return {
            'url': location.get_absolute_url(),
            'title': location.name
        }
    return {
        'url': reverse('albums'),
        'title': _('Albums')
    }


@login_required
def list(request):
    paginator, queryset = paginate(
        request, Album.objects.all(), settings.PHOTOS_PER_PAGE)
    context = {'paginator': paginator, 'album_list': queryset}
    return render(request, 'photos/album_list.html', context)


@login_required
def detail(request, pk, **kwargs):
    album = get_object_or_404(Album, pk=pk)
    paginator, queryset = paginate(
        request, get_photo_queryset(album=album), settings.PHOTOS_PER_PAGE)
    context = {
        'location_pk': kwargs.get('location_pk'),
        'album': album,
        'paginator': paginator,
        'photo_list': queryset,
        'back_link': get_back_link(request, album, **kwargs)
    }
    return render(request, 'photos/album_detail.html', context)


@permission_required('photos.add_album')
def create(request):
    form = AlbumForm(request.POST or None)
    if form.is_valid():
        album = form.save()
        return json_redirect(request, album.get_absolute_url())
    context = {
        'form': form,
        'form_title': _('Create Album'),
        'form_submit': _('Save')
    }
    return json_render(request, 'photos/ajax_form.html', context)


@permission_required('photos.edit_album')
def edit(request, pk):
    album = get_object_or_404(Album, pk=pk)
    form = AlbumForm(request.POST or None, instance=album)
    if form.is_valid():
        album = form.save()
        return json_redirect(request, album.get_absolute_url())
    context = {
        'form': form,
        'form_title': _('Edit Album'),
        'form_submit': _('Save')
    }
    return json_render(request, 'photos/ajax_form.html', context)


@permission_required('photos.delete_album')
def delete(request, pk):
    album = get_object_or_404(Album, pk=pk)
    if request.POST:
        album.delete()
        return json_redirect(request, reverse('albums'))
    context = {
        'album': album,
        'form_title': _('Delete Album'),
        'form_submit': _('Delete'),
        'form_messages': (
            _('Are you sure you want to delete this album?'),
            _('This will also delete all the photos in the album.')
        )
    }
    return json_render(request, 'photos/ajax_form.html', context)


@permission_required('photos.edit_album')
def merge(request, pk):
    album = get_object_or_404(Album, pk=pk)
    form = AlbumMergeForm(request.POST or None, instance=album)
    if form.is_valid():
        album = form.save()
        return json_redirect(request, album.get_absolute_url())
    context = {
        'album': album,
        'form': form,
        'form_title': _('Merge Album'),
        'form_submit': _('Merge')
    }
    return json_render(request, 'photos/ajax_form.html', context)


@login_required
def download(request, pk):
    album = get_object_or_404(Album, pk=pk)
    temp_zip = tempfile.NamedTemporaryFile()
    with zipfile.ZipFile(temp_zip, 'w') as zipf:
        for photo in album.photo_set.all():
            full_path = os.path.join(settings.MEDIA_ROOT, photo.file.name)
            zipf.write(full_path, '%s' % (photo.file.name.split('/')[-1]))
    temp_zip.seek(0)
    response = HttpResponse(temp_zip.read(), content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename=%s.zip' % album.name
    return response

photos/views/location.py
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404

from photos.forms import LocationRenameForm
from photos.models import Location
from stream.utils import send_action
from utils.paginate import paginate
from utils.views import json_redirect, json_render


@login_required
def list(request):
    paginator, queryset = paginate(
        request, Location.objects.all(), settings.PHOTOS_PER_PAGE)
    context = {'paginator': paginator, 'location_list': queryset}
    return render(request, 'photos/location_list.html', context)


@login_required
def detail(request, pk):
    location = get_object_or_404(Location, pk=pk)
    paginator, queryset = paginate(
        request, location.album_set.all(), settings.PHOTOS_PER_PAGE)
    context = {
        'location': location,
        'paginator': paginator,
        'album_list': queryset,
        'back_link': {'url': reverse('locations'), 'title': _('Locations')}
    }
    return render(request, 'photos/location_detail.html', context)


@permission_required('photos.add_location')
def create(request):
    form = LocationRenameForm(request.POST or None)
    if form.is_valid():
        location = form.save()
        send_action(
            request.user,
            'created the location',
            target=location)
        return json_redirect(request, location.get_absolute_url())
    context = {
        'form': form,
        'form_title': _('Create Location'),
        'form_submit': _('Save')
    }
    return json_render(request, 'photos/ajax_form.html', context)


@permission_required('photos.edit_location')
def rename(request, pk):
    location = get_object_or_404(Location, pk=pk)
    form = LocationRenameForm(request.POST or None, instance=location)
    if form.is_valid():
        location = form.save()
        return json_redirect(request, location.get_absolute_url())
    context = {
        'form': form,
        'form_title': _('Rename Location'),
        'form_submit': _('Save')
    }
    return json_render(request, 'photos/ajax_form.html', context)


@permission_required('photos.delete_location')
def delete(request, pk):
    location = get_object_or_404(Location, pk=pk)
    if request.POST:
        location.delete()
        return json_redirect(request, reverse('locations'))
    context = {
        'location': location,
        'form_title': _('Delete Location'),
        'form_submit': _('Delete'),
        'form_messages': (
            _('Are you sure you want to delete this location?'),
            _('This will also remove this location from any albums.')
        )
    }
    return json_render(request, 'photos/ajax_form.html', context)

photos/templates/photos/ajax_form.html
{% load i18n %}
<h2>{{ form_title }}</h2>
<form method="post" action="{{ request.path }}">
    {% for message in form_messages %}
        <p>{{ message }}</p>
    {% endfor %}
    {% include '_form.html' %}
    <div class="buttons">
        <input type="button" class="cancel" value="{% trans 'Cancel' %}">
        <input type="submit" value="{{ form_submit }}">
    </div>
</form>

photos/templates/photos/album_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{{ album.name }}{% endblock %}
{% block header %}{{ album.name }}{% endblock %}

{% block actions %}
    <div class="actions album-actions">
        {% if perms.photos.change_album %}
            <a href="{% url 'album_edit' album.pk %}" data-modal="form">{% trans 'Edit' %}</a>
            <a href="{% url 'album_merge' album.pk %}" data-modal="form">{% trans 'Merge' %}</a>
        {% endif %}
        {% if perms.photos.delete_album %}
            <a href="{% url 'album_delete' album.pk %}" data-modal="form">{% trans 'Delete' %}</a>
        {% endif %}
        <a href="{% url 'album_download' album.pk %}">{% trans 'Download' %}</a>
    </div>
{% endblock %}

{% block content %}
    <div class="photo-list">
        {% for photo in photo_list %}
            <div class="thumb">
                {% if location_pk %}
                    {% url 'photo' pk=photo.pk album_pk=album.pk location_pk=location_pk as photo_url %}
                {% else %}
                    {% url 'photo' pk=photo.pk as photo_url %}
                {% endif %}
                <a href="{{ photo_url }}">
                    <img src="{{ photo.file_200x200.url }}" alt="{{ photo.name }}">
                </a>
            </div>
        {% endfor %}
        <div class="clear"></div>
    </div>
{% endblock %}

photos/templates/photos/album_list.html
{% extends 'base.html' %}

{% load i18n %}
{% load humanize %}

{% block title %}{% trans 'Albums' %}{% endblock %}
{% block header %}{% trans 'Albums' %}{% endblock %}

{% block actions %}
    <span class="actions album-actions">
        {% if perms.photos.add_album %}
            <a href="{% url 'album_create' %}" data-modal="form">{% trans 'Create Album' %}</a>
        {% endif %}
    </span>
{% endblock %}

{% block content %}
    <div class="album-list">
        {% for album in album_list %}
            <div class="thumb">
                <a href="{{ album.get_absolute_url }}">
                    {% if album.cover_photo %}
                        <img src="{{ album.cover_photo.file_200x200.url|default:'' }}" alt="{{ album.name }}">
                    {% else %}
                        <img src="{{ STATIC_URL }}/img/cover-blank.png">
                    {% endif %}
                    <div class="name">{{ album.name|truncatechars:"45" }}</div>
                    {% with count=album.photo_set.count %}
                        <div class="count">
                            {% blocktrans count counter=count with total=count|intcomma %}
                                {{ total }} photo
                            {% plural %}
                                {{ total }} photos
                            {% endblocktrans %}
                        </div>
                    {% endwith %}
                </a>
            </div>
        {% endfor %}
        <div class="clear"></div>
    </div>
{% endblock %}

photos/templates/photos/location_detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load humanize %}

{% block title %}{{ location.name }}{% endblock %}
{% block header %}{{ location.name }}{% endblock %}

{% block actions %}
    <div class="actions location-actions">
        {% if perms.photos.change_location %}
            <a href="{% url 'location_rename' location.pk %}" data-modal="form">{% trans 'Rename' %}</a>
        {% endif %}
        {% if perms.photos.delete_location %}
            <a href="{% url 'location_delete' location.pk %}" data-modal="form">{% trans 'Delete' %}</a>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <div class="album-list">
        {% for album in album_list %}
            <div class="thumb">
                <a href="{% url 'album' pk=album.pk location_pk=location.pk %}">
                    {% if album.cover_photo %}
                        <img src="{{ album.cover_photo.file_200x200.url|default:"" }}" alt="{{ album.name }}">
                    {% else %}
                        <img src="{{ STATIC_URL }}/img/cover-blank.png">
                    {% endif %}
                    <div class="name">{{ album.name|truncatechars:"45" }}</div>
                    {% with count=album.photo_set.count %}
                        <div class="count">
                            {% blocktrans count counter=count with total=count|intcomma %}
                                {{ total }} photo
                            {% plural %}
                                {{ total }} photos
                            {% endblocktrans %}
                        </div>
                    {% endwith %}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

photos/templates/photos/location_list.html
{% extends 'base.html' %}

{% load i18n %}
{% load humanize %}

{% block title %}{% trans 'Locations' %}{% endblock %}
{% block header %}{% trans 'Locations' %}{% endblock %}

{% block actions %}
    <span class="actions location-actions">
        {% if perms.photos.add_location %}
            <a href="{% url 'location_create' %}" data-modal="form">{% trans 'Create Location' %}</a>
        {% endif %}
    </span>
{% endblock %}

{% block content %}
    <div class="album-list">
        {% for location in location_list %}
            <div class="thumb">
                <a href="{{ location.get_absolute_url }}">
                    {% if location.cover_photo %}
                        <img src="{{ location.cover_photo.file_200x200.url|default:"" }}" alt="{{ location.name }}">
                    {% else %}
                        <img src="{{ STATIC_URL }}/img/cover-blank.png">
                    {% endif %}
                    <div class="name">{{ location.name|truncatechars:"45" }}</div>
                    {% with count=location.album_set.count %}
                        <div class="count">
                            {% blocktrans count counter=count with total=count|intcomma %}
                                {{ total }} album
                            {% plural %}
                                {{ total }} albums
                            {% endblocktrans %}
                        </div>
                    {% endwith %}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

photos/templates/photos/person_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{{ person.name }}{% endblock %}
{% block header %}{{ person.name }}{% endblock %}

{% block actions %}
    <div class="actions person-actions">
        {% if perms.photos.change_person %}
            <a href="{% url 'person_rename' person.pk %}" data-modal="form">{% trans 'Rename' %}</a>
        {% endif %}
        {% if perms.photos.delete_person %}
            <a href="{% url 'person_delete' person.pk %}" data-modal="form">{% trans 'Delete' %}</a>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <div class="photo-list">
        {% for photo in photo_list %}
            <div class="thumb">
                <a href="{% url 'photo' pk=photo.pk person_pk=person.pk %}">
                    <img src="{{ photo.file_200x200.url }}" alt="{{ photo.name }}">
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

photos/templates/photos/person_list.html
{% extends 'base.html' %}

{% load humanize %}
{% load i18n %}

{% block title %}{% trans 'People' %}{% endblock %}
{% block header %}{% trans 'People' %}{% endblock %}

{% block actions %}
    <span class="actions person-actions">
        {% if perms.photos.add_person %}
            <a href="{% url 'person_create' %}" data-modal="form">{% trans 'Create Person' %}</a>
        {% endif %}
    </span>
{% endblock %}

{% block content %}
    <div class="album-list">
        {% for person in person_list %}
            <div class="thumb">
                <a href="{{ person.get_absolute_url }}">
                    {% if person.cover_photo %}
                        <img src="{{ person.cover_photo.file_200x200.url|default:"" }}" alt="{{ person.name }}">
                    {% else %}
                        <img src="{{ STATIC_URL }}/img/cover-blank.png">
                    {% endif %}
                    <div class="name">{{ person.name|truncatechars:"45" }}</div>
                    {% with count=person.photo_set.count %}
                        <div class="count">
                            {% blocktrans count counter=count with total=count|intcomma %}
                                {{ total }} photo
                            {% plural %}
                                {{ total }} photos
                            {% endblocktrans %}
                        </div>
                    {% endwith %}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

photos/templates/photos/photo_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{{ photo.album.name }}{% endblock %}
{% block header %}{{ photo.album.name }}{% endblock %}

{% block pagination %}

    {% if paginator.has_previous %}
        <a href="{{ paginator.previous_url }}" class="previous" data-navigate="left">&lt&lt; Prev</a>
    {% else %}
        <span class="previous">&lt&lt; Prev</span>
    {% endif %}

    <span class="count">
        {{ paginator.index }} {% trans 'of' %} {{ paginator.count }}
    </span>

    {% if paginator.has_next %}
        <a href="{{ paginator.next_url }}" class="next" data-navigate="right">Next &gt;&gt;</a>
    {% else %}
        <span class="next">Next &gt;&gt;</span>
    {% endif %}

{% endblock %}

{% block actions %}
    <div class="actions photo-actions">
        {% if perms.photos.change_photo %}
            <a href="{% url 'photo_rotate' photo.pk %}" data-modal="rotate">{% trans 'Rotate' %}</a>
            <a href="{% url 'photo_rename' photo.pk %}" data-modal="form">{% trans 'Rename' %}</a>
            <a href="{% url 'photo_move' photo.pk %}" data-modal="form">{% trans 'Move' %}</a>
            <a href="{% url 'photo_tag' photo.pk %}" data-modal="form">{% trans 'Tag' %}</a>
        {% endif %}
        {% if perms.photos.delete_photo %}
            <a href="{% url 'photo_delete' photo.pk %}" data-modal="form">{% trans 'Delete' %}</a>
        {% endif %}
        <a href="{% url 'photo_download' photo.pk %}">{% trans 'Download' %}</a>
    </div>
{% endblock %}

{% block content %}
    <div class="photo-main">
        <div class="photo">
            <img src="{{ photo.file_800x600.url }}" alt="{{ photo.name }}">
        </div>
        <div class="name">{{ photo.name }}</div>
    </div>
{% endblock %}

photos/templates/photos/search.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Search' %}{% endblock %}
{% block header %}{% trans 'Search' %}{% endblock %}

{% block width %}small{% endblock %}

{% block content %}
    <form method="post" action="{{ request.path }}" class="search">
        {% include '_form.html' %}
        <div class="buttons">
            <input type="submit" value="{% trans 'Search' %}">
        </div>
    </form>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(function() {
            $("form select").chosen();
        });
    </script>
{% endblock %}

photos/templates/photos/search_results.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Results' %}{% endblock %}
{% block header %}{% trans 'Results' %}{% endblock %}

{% block content %}
    <div class="photo-list">
        {% for photo in photo_list %}
            <div class="thumb">
                <a href="{% url 'photo' pk=photo.pk query=query %}">
                    <img src="{{ photo.file_200x200.url }}" alt="{{ photo.name }}">
                </a>
            </div>
        {% endfor %}
        <div class="clear"></div>
    </div>
{% endblock %}

photos/templates/photos/upload.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Upload' %}{% endblock %}
{% block header %}{% trans 'Upload' %}{% endblock %}

{% block width %}small{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" action="{{ request.path }}">
        {% include '_form.html' %}
        <div class="buttons">
            <input type="submit" value="{% trans 'Upload' %}">
        </div>
    </form>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(function() {
            $("form select").chosen();
        });
    </script>
{% endblock %}