gallery/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from stream.views import action_list

urlpatterns = patterns(
    '',
    url(r'^$', action_list, name='home'),
    url(r'^auth/', include('accounts.urls', 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('photos.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/urls.py
from django.conf.urls import patterns, url

from photos import views
from photos.views import album, photo, person, location

urlpatterns = patterns(
    '',
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<query>[\w=&]+)/$', views.results, name='results'),

    url(r'^albums/$', album.list, name='albums'),
    url(r'^albums/create.ajax/$', album.create, name='album_create'),
    url(r'^albums/(?P<pk>\d+)/$', album.detail, name='album'),
    url(r'^albums/(?P<pk>\d+)/edit.ajax/$', album.edit, name='album_edit'),
    url(r'^albums/(?P<pk>\d+)/delete.ajax/$', album.delete,
        name='album_delete'),
    url(r'^albums/(?P<pk>\d+)/merge.ajax/$', album.merge,
        name='album_merge'),
    url(r'^albums/(?P<pk>\d+)/download/$', album.download,
        name='album_download'),

    url(r'^locations/$', location.list, name='locations'),
    url(r'^locations/create.ajax/$', location.create,
        name='location_create'),
    url(r'^locations/(?P<pk>\d+)/$', location.detail, name='location'),
    url(r'^locations/(?P<pk>\d+)/rename.ajax/$', location.rename,
        name='location_rename'),
    url(r'^locations/(?P<pk>\d+)/delete.ajax/$', location.delete,
        name='location_delete'),

    url(r'^people/$', person.list, name='people'),
    url(r'^people/create.ajax/$', person.create, name='person_create'),
    url(r'^people/(?P<pk>\d+)/$', person.detail, name='person'),
    url(r'^people/(?P<pk>\d+)/rename.ajax/$', person.rename,
        name='person_rename'),
    url(r'^people/(?P<pk>\d+)/delete.ajax/$', person.delete,
        name='person_delete'),

    url(r'^photos/(?P<pk>\d+)/$', photo.detail, name='photo'),
    url(r'^photos/(?P<pk>\d+)/rotate.ajax/$', photo.rotate,
        name='photo_rotate'),
    url(r'^photos/(?P<pk>\d+)/move.ajax/$', photo.move, name='photo_move'),
    url(r'^photos/(?P<pk>\d+)/rename.ajax/$', photo.rename,
        name='photo_rename'),
    url(r'^photos/(?P<pk>\d+)/tag.ajax/$', photo.tag, name='photo_tag'),
    url(r'^photos/(?P<pk>\d+)/delete.ajax/$', photo.delete,
        name='photo_delete'),
    url(r'^photos/(?P<pk>\d+)/download/$', photo.download,
        name='photo_download'),

    # alternate ways to get to an album
    url(r'^locations/(?P<location_pk>\d+)/albums/(?P<pk>\d+)/$',
        album.detail, name='album'),

    # alternate ways to get to a photo
    url(r'^locations/(?P<location_pk>\d+)/albums/(?P<album_pk>\d+)/photos/(?P<pk>\d+)/$',
        photo.detail, name='photo'),
    url(r'^people/(?P<person_pk>\d+)/photos/(?P<pk>\d+)/$', photo.detail,
        name='photo'),
    url(r'^search/(?P<query>[\w=&]+)/photos/(?P<pk>\d+)/$', photo.detail,
        name='photo'),
)

photos/models.py
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _

from utils.filestorage.uploads import get_unique_upload_path
from utils.filestorage.signals import delete_files_on_delete, \
    delete_files_on_change
from photos.utils import generate_thumbnail

MONTH_CHOICES = ((mon, datetime.date(2000, mon, 1).strftime('%B')) for mon in
                 range(1, 13))

YEAR_CHOICES = ((year, year) for year in
                range(1950, (datetime.datetime.now().year + 1)))


class Location(models.Model):
    """A location is a physical location that can be applied to an album."""

    name = models.CharField(_('name'), max_length=200)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('location')
        verbose_name_plural = _('locations')

    @models.permalink
    def get_absolute_url(self):
        return ('location', [str(self.id)])

    def __str__(self):
        return self.name

    @property
    def cover_photo(self):
        """
        Returns the cover photo for this person, which for now is just the
        first photo from the first album based on whatever ordering is the
        default.
        """
        return self.album_set.first().photo_set.first()


class Person(models.Model):
    """A person is an actual person that can be tagged in photos."""

    name = models.CharField(_('name'), max_length=200)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('person')
        verbose_name_plural = _('people')

    @models.permalink
    def get_absolute_url(self):
        return ('person', [str(self.id)])

    def __str__(self):
        return self.name

    @property
    def cover_photo(self):
        """
        Returns the cover photo for this person, which for now is just the
        first photo based on whatever ordering is the default.
        """
        return self.photo_set.first()


class Album(models.Model):
    """
    An album is a collection of photos. It belongs to a location and can also
    have a month and a year associated with it.
    """

    name = models.CharField(_('name'), max_length=200)
    month = models.PositiveSmallIntegerField(
        _('month'), null=True, blank=True, choices=MONTH_CHOICES)
    year = models.PositiveSmallIntegerField(
        _('year'), null=True, blank=True, choices=YEAR_CHOICES)

    location = models.ForeignKey(
        Location, null=True, blank=True,
        verbose_name=_('location'), on_delete=models.SET_NULL)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('album')
        verbose_name_plural = _('albums')

    @models.permalink
    def get_absolute_url(self):
        return ('album', [str(self.id)])

    def __str__(self):
        return self.name

    @property
    def cover_photo(self):
        """
        Returns the cover photo for this album, which for now is just the
        first photo based on whatever ordering is the default.
        """
        return self.photo_set.first()

    def get_date_display(self):
        """
        Returns a pretty display of the month and year in one of the formats:
        - 'January 2014'
        - 'January'
        - '2014'
        """
        output = []
        if self.month:
            output.append(str(self.get_month_display()))
        if self.year:
            output.append(str(self.get_year_display()))
        return ' '.join(output)


class Photo(models.Model):
    """
    A photo is just that - a single photo. It can belong to only one album.
    """

    name = models.CharField(_('name'), max_length=200, null=True, blank=True)
    file = models.ImageField(_('file'), upload_to=get_unique_upload_path)

    album = models.ForeignKey(Album, verbose_name=_('album'))
    people = models.ManyToManyField(
        Person, blank=True, verbose_name=_('people'))

    # exif_make = models.CharField(max_length=100, null=True, blank=True)
    # exif_model = models.CharField(max_length=100, null=True, blank=True)
    # exif_iso = models.PositiveSmallIntegerField(null=True, blank=True)
    # exif_focal = models.PositiveSmallIntegerField(null=True, blank=True)
    # exif_exposure = models.CharField(max_length=100, null=True, blank=True)
    # exif_fnumber = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        ordering = ['name', ]
        verbose_name = _('photo')
        verbose_name_plural = _('photos')

    @models.permalink
    def get_absolute_url(self):
        return ('photo', [str(self.id)])

    def __str__(self):
        return self.name

    def thumbnail(self, size):
        """
        Generate and return a thumbnail with the given size. Only do this once
        in this instance to save on hits to the Thumnail model.
        """
        prop_name = '_thumbnail_%s' % size.replace('-', '_')
        if not hasattr(self, prop_name):
            setattr(
                self,
                prop_name,
                self.thumbnail_set.get_or_create(size=size)[0].file)
        return getattr(self, prop_name)

    @property
    def file_200x200(self):
        """
        Shortcut to generate a '200x200-fit' thumbnail. Useful in templates.
        """
        return self.thumbnail('200x200-fit')

    @property
    def file_800x600(self):
        """
        Shortcut to generate a '800x600-thumb' thumbnail. Useful in templates.
        """
        return self.thumbnail('800x600-thumb')


class Thumbnail(models.Model):
    """
    A thumbnail is a smaller resolution size of a photo. It knows how to
    generate itself once it has a size and a photo associated to it.
    """

    size = models.CharField(_('size'), max_length=20, db_index=True)
    file = models.ImageField(_('file'))
    photo = models.ForeignKey(Photo, verbose_name=_('photo'))

    class Meta:
        ordering = ['photo', 'size', ]
        unique_together = ('photo', 'size', )
        verbose_name = _('thumbnail')
        verbose_name_plural = _('thumbnails')

    def __str__(self):
        return '%s (%s)' % (self.photo, self.size)

    def generate(self):
        """
        Generate the thumbnail. This happens regardless of whether we already
        have one generated. The new one will overwrite the existing one (while
        keeping the same filename).
        """
        self.file = generate_thumbnail(self.photo.file, self.size)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        """
        If we have a photo and a size, generate a thumbnail regardless of
        whether we already have one generated. Maybe in the future this could
        check to make sure the thumbnail already exists, but that's
        not needed now.
        """
        if self.photo and self.size:
            self.generate()
        super().save(force_insert, force_update, using, update_fields)

# Delete photo files when Photo instance is deleted.
models.signals.pre_delete.connect(delete_files_on_delete, sender=Photo)
models.signals.pre_save.connect(delete_files_on_change, sender=Photo)

# Delete thumbnail files when Thumbnail is deleted.
models.signals.pre_delete.connect(delete_files_on_delete, sender=Thumbnail)
models.signals.pre_save.connect(delete_files_on_change, sender=Thumbnail)

gallery/templates/_form.html
<div style="display:none">{% csrf_token %}</div>

{% if form.non_field_errors %}
    <ul class="errors non-field-errors">
        {% for err in form.non_field_errors %}
            <li>{{ err }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% for hidden in form.hidden_fields %}
    <div style="display:none">{{ hidden }}</div>
{% endfor %}

{% for field in form.visible_fields %}
    <div class="field {% if field.errors %}field-with-errors{% endif %}">
        {% if field.errors %}
            <ul class="errors">
                {% for err in field.errors %}
                  <li>{{ err }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if field.is_checkbox %}
            <div class="checkbox">{{ field }}{{ field.label_tag }}</div>
        {% else %}
            <div class="input">
                {{ field.label_tag }}{{ field }}
                {% if field.field.help_text and not request.is_ajax %}
                    <span class="helptext">{{ field.field.help_text|safe }}</span>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endfor %}

{{ form.media }}

gallery/templates/_paginator.html
{% load i18n %}
{% load humanize %}

{% if paginator.count > 0 %}

    {% if paginator.this_page.has_previous %}
        <a href="{{ paginator.previous_url }}" class="previous" data-navigate="left">&lt&lt; {% trans 'Prev' %}</a>
    {% else %}
        <span class="previous">&lt&lt; {% trans 'Prev' %}</span>
    {% endif %}

    <span class="count">
        {{ paginator.this_page.start_index }} - {{ paginator.this_page.end_index }}
        {% trans 'of' %}
        {{ paginator.count }}
    </span>

    {% if paginator.this_page.has_next %}
        <a href="{{ paginator.next_url }}" class="next" data-navigate="right">{% trans 'Next' %} &gt;&gt;</a>
    {% else %}
        <span class="next">{% trans 'Next' %} &gt;&gt;</span>
    {% endif %}

{% endif %}

gallery/templates/base.html
<!DOCTYPE html>

{% load i18n %}
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% trans 'Photo Gallery' %} - {% block title %}Untitled Page{% endblock %}</title>
    <link href="{% static 'css/reset.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'chosen-1.1.0/chosen.css' %}" rel="stylesheet" type="text/css" media="screen">
    {% block extra_head %}{% endblock %}
</head>
<body id="body-{% block width %}large{% endblock %}">

<div id="topbar">
    <div class="title">
        <h1>
            <a href="{% url 'home' %}" data-navigate="up">{% trans 'Photo Gallery' %}</a>
            <span class="sub">{% block header %}Untitled Page{% endblock %}</span>
        </h1>
    </div>
    <div class="links">
        {% if user.is_authenticated %}
            <a href="{% url 'albums' %}">{% trans 'Albums' %}</a>
            <a href="{% url 'locations' %}">{% trans 'Locations' %}</a>
            <a href="{% url 'people' %}">{% trans 'People' %}</a>
            {% if perms.photos.add_photo %}
                <a href="{% url 'upload' %}">{% trans 'Upload' %}</a>
            {% endif %}
            <a href="{% url 'search' %}">{% trans 'Search' %}</a>
            <a href="{% url 'accounts:profile' %}">{% trans 'Profile' %}</a>
            <a href="{% url 'accounts:logout' %}">{% trans 'Logout' %}</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">{% trans 'Login' %}</a>
            <a href="{% url 'accounts:password_reset' %}">{% trans 'Forgot Password' %}</a>
            <a href="{% url 'accounts:register' %}">{% trans 'Register' %}</a>
        {% endif %}
    </div>
</div>

<div id="toolbar">
    <div class="left">
        {% if back_link %}
            <a href="{{ back_link.url }}" data-navigate="up">&lt;&lt; {{ back_link.title }}</a>
        {% endif %}
    </div>
    <div class="pagination">
        {% block pagination %}
            {% include '_paginator.html' %}
        {% endblock %}
    </div>
    <div class="right">{% block actions %}{% endblock %}</div>
</div>

{% if messages %}
    <div id="messages">
        <ul>
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div id="content">
    {% block content %}{% endblock %}
</div>

<div id="modal-wrapper"><div id="modal"></div></div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'chosen-1.1.0/chosen.jquery.js' %}"></script>
{% block extra_js %}{% endblock %}
<script>$.ajaxSetup({data:{csrfmiddlewaretoken:"{{csrf_token}}"},});</script>

</body>
</html>